# Generated by Django 3.1.5 on 2021-01-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_customer_stock_info_warhouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_stock_info',
            old_name='warhouse',
            new_name='warehouse',
        ),
    ]
