# Generated by Django 2.2.16 on 2021-01-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_stock_info',
            name='customer_name',
        ),
    ]
