# Generated by Django 2.2.16 on 2021-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210113_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_stock_info',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
