# Generated by Django 2.2.16 on 2021-01-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_customer_stock_info_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_stock_info',
            name='value',
        ),
    ]
