# Generated by Django 3.1.5 on 2021-01-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20210113_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_stock_info',
            old_name='invoice_number',
            new_name='packing_number',
        ),
    ]
