# Generated by Django 3.1.5 on 2021-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210123_1246'),
        ('stores', '0004_auto_20210124_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_stock_info',
            name='warhouse',
            field=models.ManyToManyField(default='Not specified', to='warehouse.Warehouse_Stock_info'),
        ),
    ]
