# Generated by Django 3.1.5 on 2021-01-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210123_1246'),
        ('stores', '0008_auto_20210125_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_stock_info',
            name='warehouse',
            field=models.ManyToManyField(to='warehouse.Warehouse_Stock_info'),
        ),
    ]
