# Generated by Django 3.1.5 on 2021-01-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210123_1246'),
        ('stores', '0009_auto_20210125_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_stock_info',
            name='warehouse',
            field=models.ManyToManyField(blank=True, to='warehouse.Warehouse_Stock_info'),
        ),
    ]
