# Generated by Django 3.1.3 on 2020-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_stock_info',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_stock_info',
            name='value',
            field=models.IntegerField(),
        ),
    ]
