# Generated by Django 3.1.3 on 2020-12-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('product_description', models.CharField(max_length=256)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
