# Generated by Django 3.1.3 on 2020-12-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201203_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='basket',
            field=models.ImageField(upload_to=''),
        ),
    ]
