# Generated by Django 3.1.3 on 2020-12-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201203_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='basket',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Game\\Project\\project\\media'),
        ),
    ]
