# Generated by Django 3.1.3 on 2020-12-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201203_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='basket',
        ),
    ]
