# Generated by Django 3.1.3 on 2020-12-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='sku',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='product_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
