# Generated by Django 3.1.3 on 2020-12-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20201209_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product_description',
            field=models.CharField(max_length=256),
        ),
    ]
