# Generated by Django 2.2.16 on 2021-01-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210114_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='value',
        ),
    ]
