# Generated by Django 3.1.5 on 2021-01-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse_stock_info',
            old_name='area',
            new_name='warehouse_location',
        ),
        migrations.RenameField(
            model_name='warehouse_stock_info',
            old_name='country',
            new_name='warehouse_name',
        ),
        migrations.RemoveField(
            model_name='warehouse_stock_info',
            name='city',
        ),
        migrations.RemoveField(
            model_name='warehouse_stock_info',
            name='store_name',
        ),
        migrations.AddField(
            model_name='warehouse_stock_info',
            name='in_packing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse_stock_info',
            name='purchase_date',
            field=models.DateField(default='2018-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse_stock_info',
            name='warehouse_type',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
    ]
