# Generated by Django 2.2.16 on 2021-01-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=64)),
                ('invoice_date', models.DateField()),
                ('sku', models.CharField(max_length=64)),
                ('product_description', models.CharField(max_length=256)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
