# Generated by Django 3.1.5 on 2021-01-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210125_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, default='2018-01-01'),
            preserve_default=False,
        ),
    ]
