# Generated by Django 3.1.3 on 2020-12-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry_view', '0002_auto_20201125_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Stock_info',
        ),
    ]
