# Generated by Django 3.1.3 on 2020-12-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='basket',
            field=models.ImageField(default='basket', upload_to='basket'),
        ),
    ]
