# Generated by Django 3.1.3 on 2020-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='basket',
            field=models.ImageField(default='basket', upload_to='static/basket'),
        ),
    ]
